---
# Minio S3 setup
# https://docs.min.io/

# https://linuxconfig.org/how-to-create-systemd-service-unit-in-linux
- name: Copy minio.service file to /etc/systemd/system
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service

# Used to allow autostart of service on pi
# Now you no longer have to run this command.
# sudo systemctl enable myscript.service
- name: Allow minio.service autostart by createing a symbolic link
  file:
    src: /etc/systemd/system/minio.service
    dest: /etc/systemd/system/multi-user.target.wants/minio.service
    owner: root
    group: root
    state: link


- name: Replace /etc/profile w/ template containing Environement Vars
  template:
    src: profile.j2
    dest: /etc/profile

- include: open-ports.yml

- name: "Create s3 folder {{ s3_dir }}"
  file:
    path: "{{ s3_dir }}"
    state: directory
    mode: '0766'
  when: make_s3_dir

# https://docs.min.io/docs/minio-quickstart-guide.html
- name: Download minio server
  get_url:
    url: https://dl.minio.io/server/minio/release/linux-amd64/minio
    dest: /usr/local/bin
    mode: '0770'

# https://docs.min.io/docs/minio-client-quickstart-guide.html
- name: Download minio client
  get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: /usr/local/bin
    mode: '0755'

- name: start minio service
  command: systemctl start minio.service
